export const Questions = [{
    question : 'You`ve stumbled upon a Time-Turner, capable of altering time itself. What do you do?',
    answers : [{answer : 'You immediately use it to go back and right a wrong, no matter the consequences to the timeline.' , trait : 'Courage'},
         {answer : 'You study it carefully, weighing the potential wisdom in using such a powerful object, before deciding whether to act.', trait : 'Inteligence' },
         {answer : 'You decide that such power is too risky and choose to leave it where it is, trusting that the future will work itself out.' , trait : 'Loyalty' },
         {answer : 'You see it as an opportunity to change your future for the better, planning how best to use the Time-Turner for your own success.' , trait : 'Cunning' }],
},{
    question : 'While exploring the Room of Requirement, you find a hidden door leading to a powerful magical artifact an Elder Wand. What do you do?',
    answers : [{answer : 'You immediately take the wand, eager to test its power, regardless of the consequences' , trait : 'Courage'},
         {answer : 'You pause to study the wand`s history and understand its origins, seeking to learn its true potential before making a move.', trait : 'Inteligence' },
         {answer : 'You decide it`s too dangerous and walk away, believing that no one should wield such immense power alone' , trait : 'Loyalty' },
         {answer : ' You recognize the wand`s power but are determined to use it strategically, thinking of how to leverage its strength for your own goals.' , trait : 'Cunning' }],
},{
    question : 'You are granted the opportunity to work with a Centaur to help solve a magical mystery. What is your role in the partnership?',
    answers : [{answer : 'You take charge, showing your bravery and confidence, ready to lead the partnership and face the mystery head-on.' , trait : 'Courage'},
         {answer : 'You are eager to learn from the Centaur`s wisdom, taking a backseat in the partnership to observe and absorb as much knowledge as possible', trait : 'Inteligence' },
         {answer : 'You focus on the practical tasks, ensuring that you help in a way that`s fair and loyal to both your partner and the task at hand' , trait : 'Loyalty' },
         {answer : 'You think strategically, using your resourcefulness to guide the partnership toward finding the quickest and most effective solution to the mystery' , trait : 'Cunning' }],
},{
    question : 'You find yourself facing a Griffin guarding an entrance to a secret library. What do you do?',
    answers : [{answer : 'You boldly approach, confident that you can tame the Griffin or defeat it in a challenge.' , trait : 'Courage'},
         {answer : 'You study the Griffin carefully, trying to understand its behavior and figuring out how to gain its trust.', trait : 'Inteligence' },
         {answer : 'You take your time, considering all possibilities and seeking a peaceful solution that benefits both you and the Griffin.' , trait : 'Loyalty' },
         {answer : 'You use your wit to think of a clever way to outsmart the Griffin and bypass it to reach your goal. ' , trait : 'Cunning' }],
},{
    question : 'A House-Elf offers you the chance to take one item from the Hogwarts kitchens. What do you choose?',
    answers : [{answer : ' You choose a powerful artifact, knowing it could help you face any challenge or enemy in your path.' , trait : 'Courage'},
         {answer : 'You choose a book of magical recipes, excited to learn new spells and potions through creativity', trait : 'Inteligence' },
         {answer : 'You choose a simple, hearty meal, preferring to enjoy a reward that will sustain you through hard work and patience.' , trait : 'Loyalty' },
         {answer : 'You choose a rare, valuable item that could give you an edge in your goals, seeing it as a means to your success.' , trait : 'Cunning' }],
},{
    question : 'You`re walking through the Forbidden Forest at night, and suddenly you encounter a Thestral. How do you approach the situation?',
    answers : [{answer : 'Stand your ground, ready to face the Thestral head-on. You`re not afraid of any danger.', trait : 'Courage'},
         {answer : 'Observe the Thestral from a distance, trying to learn about it before taking any action', trait : 'Inteligence' },
         {answer : 'Approach the Thestral slowly, showing it that you`re calm and trustworthy. You`re hoping to form a bond' , trait : 'Loyalty' },
         {answer : 'Quickly assess the situation and decide what will help you achieve your goal most effectively—whether it means befriending or outwitting the  Thestral ' , trait : 'Cunning' }],
},{
    question : 'You discover an ancient  Runestone  that holds the key to a hidden treasure. How do you tackle it?',
    answers : [{answer : 'You dive straight into solving it, trusting your instincts and courage to guide you' , trait : 'Courage'},
         {answer : 'You take your time to think through each clue carefully, using your Inteligence and wit to decipher the  Runestone', trait : 'Inteligence' },
         {answer : 'You try to approach the riddle with patience and humility, considering all possibilities before jumping to conclusions. ' , trait : 'Loyalty' },
         {answer : 'You try to quickly find the most efficient way to solve the riddle, thinking ahead to what the treasure might offer you' , trait : 'Cunning' }],
},{
    question : 'You’ve just received an invitation to a duel with a fellow student. How do you feel about this challenge?',
    answers : [{answer : ' Excited and ready to show your strength and skills.' , trait : 'Courage'},
         {answer : 'Curious about how the duel works and eager to learn from the experience, even if it’s a bit dangerous', trait : 'Inteligence' },
         {answer : 'You’re determined to make sure the duel is fair, ensuring everyone follows the rules. You may even try to mediate if things get too heated.' , trait : 'Loyalty' },
         {answer : 'You begin strategizing, making sure your move will give you the advantage—whether it’s a fair duel or not.  ' , trait : 'Cunning' }],
},{
    question : 'A Vampire approaches you with an offer to teach you ancient magical spells. How do you respond?',
    answers : [{answer : 'You accept without hesitation, excited to learn dark magic and prove your strength by mastering it' , trait : 'Courage'},
         {answer : 'You ask many questions about the spells, intrigued by the knowledge and eager to understand the full scope of the magical art. ', trait : 'Inteligence' },
         {answer : 'You’re cautious and ask the  Vampire  to demonstrate the ethics of the spells, ensuring they are used for good and not harm.' , trait : 'Loyalty' },
         {answer : 'You see it as an opportunity to gain power and decide to only learn the most beneficial spells for your own advancement. ' , trait : 'Cunning' }],
}];
